//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMembership
    {
        public int CM_ID { get; set; }
        public string CustMembershipID { get; set; }
        public int CustomerID { get; set; }
        public int MembershipID { get; set; }
        public System.DateTime DateFrom { get; set; }
        public int Months { get; set; }
        public System.DateTime DateTo { get; set; }
        public decimal ChargesPerMonth { get; set; }
        public decimal DiscountPer { get; set; }
        public decimal TotalCharges { get; set; }
        public System.DateTime BillDate { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TotalPaid { get; set; }
        public decimal Balance { get; set; }
        public decimal DiscountAmount { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
