//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public Registration()
        {
            this.Logs = new HashSet<Log>();
        }
    
        public string UserID { get; set; }
        public string UserType { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string ContactNo { get; set; }
        public string EmailID { get; set; }
        public System.DateTime JoiningDate { get; set; }
    
        public virtual ICollection<Log> Logs { get; set; }
    }
}
