//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public Subscription()
        {
            this.CustomerMemberships = new HashSet<CustomerMembership>();
        }
    
        public int M_ID { get; set; }
        public string Type { get; set; }
        public decimal ChargesPerMonth { get; set; }
    
        public virtual ICollection<CustomerMembership> CustomerMemberships { get; set; }
    }
}
